### ISSUE TITLE
Compile in IDEA

### ISSUE THREAD

**Issue by stdex** [Novanoid/Tourney#1]
Hi.
Oracle JDK 1.8.0.25
1. I'm try to import this eclipse project to IDEA and there are some warning in it:

/src/usspg31/tourney/controller/dialogs/PasswordSelectionDialog.java
Error:(112, 33) java: variable retryTimer might not have been initialized
Error:(123, 29) java: variable retryTimer might not have been initialized

/src/usspg31/tourney/controller/dialogs/PasswordDialog.java
Error:(81, 33) java: variable retryTimer might not have been initialized
Error:(92, 29) java: variable retryTimer might not have been initialized

/src/usspg31/tourney/model/undo/UndoManager.java
Error:(270, 13) java: reference to addListener is ambiguous
  both method addListener(javafx.beans.InvalidationListener) in javafx.beans.Observable and method addListener(javafx.collections.ListChangeListener<? super E>) in javafx.collections.ObservableList match
Error:(270, 26) java: incompatible types: invalid method reference
    method listChangeListener in class usspg31.tourney.model.undo.UndoManager cannot be applied to given types
      required: javafx.collections.ListChangeListener.Change<? extends T>
      found: javafx.beans.Observable
      reason: cannot infer type-variable(s) T
        (argument mismatch; javafx.beans.Observable cannot be converted to javafx.collections.ListChangeListener.Change<? extends T>)
Error:(283, 13) java: reference to removeListener is ambiguous
  both method removeListener(javafx.beans.InvalidationListener) in javafx.beans.Observable and method removeListener(javafx.collections.ListChangeListener<? super E>) in javafx.collections.ObservableList match
Error:(283, 29) java: incompatible types: invalid method reference
    method listChangeListener in class usspg31.tourney.model.undo.UndoManager cannot be applied to given types
      required: javafx.collections.ListChangeListener.Change<? extends T>
      found: javafx.beans.Observable
      reason: cannot infer type-variable(s) T
        (argument mismatch; javafx.beans.Observable cannot be converted to javafx.collections.ListChangeListener.Change<? extends T>)
1. Could you add multilanguage interface for this project?

**Comment by jtagscherer** [comment]
Hi,

thanks for your remarks.
1. The errors you have mentioned should have been fixed by commit #b0c9dc3. In order to make things work in IntelliJ IDEA you will have to pull the fixed version, import the JUnit plugin manually or exclude the "test" folder altogether and finally mark the "res" folder as the ressources root.
2. Tourney already supports a multilanguage interface with the new default language being English. You can change the language in the settings. All strings are outsourced to language files to be found in "res/ui/language".

**Comment by stdex** [comment]
Thanks. 

Not fixed:
/src/usspg31/tourney/controller/dialogs/PasswordDialog.java
Error:(81, 33) java: variable retryTimer might not have been initialized
Error:(92, 29) java: variable retryTimer might not have been initialized

**Comment by jtagscherer** [comment]
You are right. However, it should be working now.

**Comment by stdex** [comment]
Fine. It's build correctly.
